require("common.core.keymaps")
require("common.core.options")
require("common.core.colorscheme")
require("common.plugin_manager")

require("common.plugins.cmp")
require("common.plugins.comment")
require("common.plugins.lualine")
require("common.plugins.neo-tree")
require("common.plugins.telescope")
require("common.plugins.auto-pairs")
require("common.plugins.treesitter")
require("common.plugins.autocommands")
require("common.plugins.zk")
require("common.plugins.colorizer")
require("common.plugins.bufferline")
require("common.plugins.alpha")
require("common.plugins.project")
require("common.plugins.gitsigns")
require("common.plugins.copilot")

require("common.language-server-protocol.mason")
---@diagnostic disable-next-line: different-requires
require("common.language-server-protocol.lspconfig")
require("common.language-server-protocol.lspsaga")
require("common.language-server-protocol.null-ls")
